// lib/config/cards.config.ts
// Full recommendation card library — derived from diagnostic next-steps
// Source: AiGENiQ_Recommendation_Engine_v1.xlsx diagnostic blocks
// Each dimension × level produces a card with placement (NOW/NEXT/LATER)

import { RecommendationCard } from '../../types';

export const recommendationCards: RecommendationCard[] = [
    // ── D1: Data & Knowledge Foundations ──
    {
        id: 'D1-NOW',
        title: 'Establish a Single Source of Truth for Client Data',
        placement: 'NOW',
        triggerDimension: 'D1',
        triggerThreshold: 4.5,
        ownerRole: 'Data Owner / Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Name one person as your Data Owner',
            'Audit the top 3 places your client data currently lives',
            'Pick one as your single source of truth and migrate everything there',
        ],
        whyItMatters: 'Every AI tool you buy will only be as useful as the data you feed it. Fragmented, inconsistent data is the single biggest blocker to AI working in your business.',
    },
    {
        id: 'D1-NEXT',
        title: 'Define a Data Quality Standard',
        placement: 'NEXT',
        triggerDimension: 'D1',
        triggerThreshold: 7.4,
        ownerRole: 'Data Owner',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Define a one-page data quality standard for your most important data set',
            'Specify what "complete and correct" looks like for each field',
            'Assign one person to audit it monthly',
        ],
        whyItMatters: 'Inconsistent data quality is the difference between AI that works reliably and AI that produces plausible-sounding but untrustworthy outputs.',
    },
    {
        id: 'D1-LATER',
        title: 'Pilot Predictive Data Use with AI',
        placement: 'LATER',
        triggerDimension: 'D1',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'Data Owner / AI Lead',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Identify one business question you currently answer by looking backwards',
            'Scope a 30-day pilot using existing data to answer it predictively',
            'Evaluate using an AI tool connected to your data',
        ],
        whyItMatters: 'Moving from reactive to predictive data use is where AI creates the most compelling business value.',
    },

    // ── D2: Leadership & Strategy ──
    {
        id: 'D2-NOW',
        title: 'Assign AI Ownership in Leadership',
        placement: 'NOW',
        triggerDimension: 'D2',
        triggerThreshold: 4.5,
        ownerRole: 'CEO / Managing Director',
        effortLevel: 'LOW',
        firstSteps: [
            'In your next leadership meeting, name who owns AI outcomes',
            'Give them one hour a week of protected time',
            'Ask them to return in two weeks with one specific use case to investigate',
        ],
        whyItMatters: 'McKinsey found that no ownership + no protected capacity + no evaluation process is more predictive of AI failure than any technology limitation.',
    },
    {
        id: 'D2-NEXT',
        title: 'Appoint an AI Lead with Regular Reviews',
        placement: 'NEXT',
        triggerDimension: 'D2',
        triggerThreshold: 7.4,
        ownerRole: 'CEO / Operations Director',
        effortLevel: 'LOW',
        firstSteps: [
            'Assign a named AI Lead with 2–3 hours a week',
            'Give them explicit authority to evaluate and propose AI initiatives',
            'Schedule monthly 30-minute reviews of active experiments',
        ],
        whyItMatters: 'Without structured execution, individual experiments never connect into anything systematic, and the organisation stays in permanent pilot mode.',
    },
    {
        id: 'D2-LATER',
        title: 'Formalise AI Strategy Document',
        placement: 'LATER',
        triggerDimension: 'D2',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'AI Lead / Leadership Team',
        effortLevel: 'LOW',
        firstSteps: [
            'Write a one-page AI strategy: three objectives for the next 12 months',
            'Define the owner, success metric, and quarterly review date for each',
            'Share and review quarterly',
        ],
        whyItMatters: 'This transforms informal alignment into institutional commitment — only 4% of companies achieve this level of leadership integration.',
    },

    // ── D3: Governance & Risk ──
    {
        id: 'D3-NOW',
        title: 'Write a Single-Page AI Usage Policy',
        placement: 'NOW',
        triggerDimension: 'D3',
        triggerThreshold: 4.5,
        ownerRole: 'Operations Lead / Compliance',
        effortLevel: 'LOW',
        firstSteps: [
            'Write a single-page policy: which tools are approved, what data must never be entered, who to contact if something goes wrong',
            'Share it with every team member',
            'Ask them to confirm they have read it',
        ],
        whyItMatters: 'Under EU AI Act 2024 and UK ICO guidance, no policy + no controls = real legal exposure. This is your most urgent governance fix.',
    },
    {
        id: 'D3-NEXT',
        title: 'Implement AI Output Review Practice',
        placement: 'NEXT',
        triggerDimension: 'D3',
        triggerThreshold: 7.4,
        ownerRole: 'Team Leads',
        effortLevel: 'LOW',
        firstSteps: [
            'For 30 days, require a 60-second factual check before sending AI outputs to clients',
            'Log any errors in a shared document',
            'Review monthly to identify which tools or tasks generate the most mistakes',
        ],
        whyItMatters: 'As you scale AI use, gaps in quality control compound — a policy read once is quickly forgotten without active checking practice.',
    },
    {
        id: 'D3-LATER',
        title: 'Quarterly AI Tool Review Process',
        placement: 'LATER',
        triggerDimension: 'D3',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'AI Lead / Compliance',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'For each approved tool, score it on output quality, data safety compliance, and team adoption',
            'Retire tools scoring poorly',
            'Maintain a current approved list the team can trust',
        ],
        whyItMatters: 'Moving from reactive to proactive governance means tracking AI performance over time and continuously improving your toolkit.',
    },

    // ── D4: People & Change Readiness ──
    {
        id: 'D4-NOW',
        title: 'Run an AI Awareness Session',
        placement: 'NOW',
        triggerDimension: 'D4',
        triggerThreshold: 4.5,
        ownerRole: 'Team Lead / HR',
        effortLevel: 'LOW',
        firstSteps: [
            'Run a 45-minute session addressing: "How might AI make each person\'s job easier?"',
            'Use real industry examples',
            'Invite the team to identify one tedious task AI could handle',
        ],
        whyItMatters: 'Fear of job displacement (not unwillingness to learn) is the primary cause of failed AI adoption. Address this before introducing any tool.',
    },
    {
        id: 'D4-NEXT',
        title: 'Appoint AI Champions per Team',
        placement: 'NEXT',
        triggerDimension: 'D4',
        triggerThreshold: 7.4,
        ownerRole: 'HR / Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Name one AI Champion per team with 2 hours/month of protected time',
            'Ask them to run one 30-minute tool demo per quarter',
            'Create a shared channel where the team logs useful prompts and tools',
        ],
        whyItMatters: 'Without recognised champions and protected learning time, adoption depends on individual enthusiasm and will be inconsistent.',
    },
    {
        id: 'D4-LATER',
        title: 'Run an AI Opportunity Sprint',
        placement: 'LATER',
        triggerDimension: 'D4',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'AI Lead / Team Leads',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Give the team 2 weeks to identify manual tasks AI could improve',
            'Document each in a shared template',
            'Prioritise top 3 by time saved × frequency for next AI pilot',
        ],
        whyItMatters: 'Channel your team\'s energy into the highest-value use cases — this turns enthusiasm into systematic value capture.',
    },

    // ── D5: Process Maturity ──
    {
        id: 'D5-NOW',
        title: 'Document Your Most Repeated Process',
        placement: 'NOW',
        triggerDimension: 'D5',
        triggerThreshold: 4.5,
        ownerRole: 'Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Pick the task your team does most often (e.g. onboarding, proposals, reporting)',
            'Spend 90 minutes writing a step-by-step description',
            'Share with the team as the new standard',
        ],
        whyItMatters: 'You cannot automate a process that has not been defined. This one document is your entire process foundation.',
    },
    {
        id: 'D5-NEXT',
        title: 'Enforce Template Compliance for 30 Days',
        placement: 'NEXT',
        triggerDimension: 'D5',
        triggerThreshold: 7.4,
        ownerRole: 'Operations Lead',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Make the template non-optional for your most critical workflow',
            'Track completion in your shared system',
            'Review friction points at month-end and fix before adding AI',
        ],
        whyItMatters: 'Process adherence that depends on individual discipline erodes over time. System-enforced consistency enables reliable automation.',
    },
    {
        id: 'D5-LATER',
        title: 'Map Processes for AI Automation Targeting',
        placement: 'LATER',
        triggerDimension: 'D5',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'Operations Lead / AI Lead',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Map top 5 processes by frequency × manual effort per occurrence',
            'Pick the top-right (high frequency, high effort) as first AI automation target',
            'Scope a 30-day pilot',
        ],
        whyItMatters: 'When processes are clearly defined, AI automation produces consistent, auditable, improvable outputs.',
    },

    // ── D6: AI Usage & Adoption ──
    {
        id: 'D6-NOW',
        title: 'Approve One AI Tool and Test It',
        placement: 'NOW',
        triggerDimension: 'D6',
        triggerThreshold: 4.5,
        ownerRole: 'AI Lead / Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Tell your team which AI tools are approved (even if just one)',
            'Pick the single most repetitive writing task',
            'Spend 30 minutes testing the approved tool against a real example',
        ],
        whyItMatters: 'Ad-hoc individual use with no institutional learning produces the lowest value and highest risk from AI.',
    },
    {
        id: 'D6-NEXT',
        title: 'Create a Shared AI Prompt Library',
        placement: 'NEXT',
        triggerDimension: 'D6',
        triggerThreshold: 7.4,
        ownerRole: 'AI Champion',
        effortLevel: 'LOW',
        firstSteps: [
            'Create a shared document with sections: the task, the prompt that works, the time it saves',
            'Ask everyone who uses AI to contribute',
            'Review in your next team meeting',
        ],
        whyItMatters: 'Prompt engineering capability — the ability to develop and share effective AI instructions — is one of the top differentiators between marginal and transformational AI benefits.',
    },
    {
        id: 'D6-LATER',
        title: 'Redesign One Workflow Around AI',
        placement: 'LATER',
        triggerDimension: 'D6',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'AI Lead / Process Owner',
        effortLevel: 'HIGH',
        firstSteps: [
            'Identify one end-to-end workflow (not just a single task)',
            'Redesign from scratch assuming AI is available at every step',
            'Map human vs AI responsibilities, then pilot for 30 days',
        ],
        whyItMatters: 'Moving from task-level to workflow-level AI is where organisations achieve transformational rather than incremental value.',
    },

    // ── D7: Tech & Integration ──
    {
        id: 'D7-NOW',
        title: 'Eliminate Your Most Painful Manual Data Entry',
        placement: 'NOW',
        triggerDimension: 'D7',
        triggerThreshold: 4.5,
        ownerRole: 'IT / Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Find the step where someone copies data between tools most frequently',
            'Investigate native integration or Zapier/Make',
            'Eliminate within two weeks',
        ],
        whyItMatters: 'Tech is the lowest-weighted dimension (8%) and most easily fixed, but disconnected systems limit which AI use cases are feasible.',
    },
    {
        id: 'D7-NEXT',
        title: 'Audit and Rationalise Your Tool Stack',
        placement: 'NEXT',
        triggerDimension: 'D7',
        triggerThreshold: 7.4,
        ownerRole: 'IT / Operations Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'List every tool the business pays for',
            'Note who owns it and whether it integrates with other core systems',
            'Remove or replace any tool with no internal owner',
        ],
        whyItMatters: 'Unowned tools are your most common source of data fragmentation. Rationalising creates a cleaner foundation for AI integration.',
    },
    {
        id: 'D7-LATER',
        title: 'Map Integration Architecture for AI Readiness',
        placement: 'LATER',
        triggerDimension: 'D7',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'IT Lead / AI Lead',
        effortLevel: 'MEDIUM',
        firstSteps: [
            'Visually map which tools connect to which',
            'Identify where data flows automatically vs manually',
            'Find one AI tool that plugs directly into an existing integration',
        ],
        whyItMatters: 'When infrastructure is AI-ready, new tools deploy without significant infrastructure work.',
    },

    // ── D8: Value & ROI Discipline ──
    {
        id: 'D8-NOW',
        title: 'Measure Your Baseline Before Any AI Trial',
        placement: 'NOW',
        triggerDimension: 'D8',
        triggerThreshold: 4.5,
        ownerRole: 'Operations Lead / AI Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'Count how many times the target task occurs per week',
            'Time how long it takes a person to complete it once',
            'Write those two numbers down — that is your baseline',
        ],
        whyItMatters: '45% of organisations struggle to prove AI ROI because they never measured the baseline. Two numbers are all you need to calculate ROI later.',
    },
    {
        id: 'D8-NEXT',
        title: 'Write a Pilot Brief for Every AI Experiment',
        placement: 'NEXT',
        triggerDimension: 'D8',
        triggerThreshold: 7.4,
        ownerRole: 'AI Lead',
        effortLevel: 'LOW',
        firstSteps: [
            'State the problem and the metric to measure success',
            'Record the baseline value today',
            'Define the threshold that tells you whether to scale or stop',
        ],
        whyItMatters: 'BCG found organisations with systematic measurement are 3x more likely to scale AI pilots to production.',
    },
    {
        id: 'D8-LATER',
        title: 'Build an AI ROI Register',
        placement: 'LATER',
        triggerDimension: 'D8',
        triggerThreshold: 10.1,
        minMaturityStage: 'scaling',
        ownerRole: 'AI Lead / Finance',
        effortLevel: 'LOW',
        firstSteps: [
            'List every AI initiative with baseline metric, target, current performance, status',
            'Review quarterly',
            'Use it to build the business case for continued AI investment',
        ],
        whyItMatters: 'Only 12% of organisations reach this level. Those that do achieve 2.8x higher value realisation from AI investments.',
    },
];
