// lib/config/diagnostics.config.ts
// Pre-written diagnostic paragraphs — 8 dimensions × 3 levels (LOW/MID/HIGH)
// Source: AiGENiQ_Recommendation_Engine_v1.xlsx → .tmp/extracted/diagnostics.json
// These are NEVER generated by an LLM. Written verbatim into the PDF report.

import { DimensionId } from '../../types';

export type DiagnosticLevel = 'LOW' | 'MID' | 'HIGH';

export interface DiagnosticBlock {
  scoreLabel: string;
  headline: string;
  diagnosis: string;
  nextStep: string;
}

export const diagnosticBlocks: Record<DimensionId, Record<DiagnosticLevel, DiagnosticBlock>> = {
  D1: {
    LOW: {
      scoreLabel: '⚠️ Critical Foundation Gap',
      headline: 'Your knowledge lives in people, not systems',
      diagnosis: 'Your answers show that critical business knowledge — client contacts, pricing, past decisions, process know-how — is stored in people\'s heads and personal files rather than in shared systems. This is the single biggest blocker to AI working in your business: every AI tool you buy will only be as useful as the data and knowledge you feed it, and right now that data is fragmented, inconsistent, or inaccessible to anyone but the person who created it. The good news is this is fixable before anything else, and fixing it creates value for your business independently of AI — even if AI never comes into the picture.',
      nextStep: 'This week, name one person as your Data Owner, audit the top 3 places your client data currently lives, pick one as your single source of truth, and move everything else there — this single action unblocks more AI use cases than any tool you could buy.',
    },
    MID: {
      scoreLabel: '🔶 Foundations Partially Built',
      headline: 'Data exists but quality and accessibility are inconsistent',
      diagnosis: 'You have made real progress — most key information lives in shared systems rather than individual files, and you use data to inform at least some decisions. The gap is consistency: your data quality varies, your knowledge base is maintained sporadically, and pulling a specific report still requires manual effort that can take hours rather than minutes. This inconsistency is the difference between AI that works reliably and AI that produces plausible-sounding but untrustworthy outputs — GenAI tools that connect to unreliable data will confidently give wrong answers.',
      nextStep: 'Define a one-page data quality standard for your single most important data set — client records, financial data, or project history — specifying what \'complete and correct\' looks like for each field, and assign one person to audit it monthly.',
    },
    HIGH: {
      scoreLabel: '✅ Strong Data Foundation',
      headline: 'Data and knowledge infrastructure is genuinely ready',
      diagnosis: 'Your data foundations are strong: knowledge is captured systematically, findable by anyone who needs it, and used actively to inform decisions — not just reported after the fact. Your organisation is in the top tier of SME data readiness, which means AI tools that connect to your data will actually produce reliable, trustworthy outputs rather than hallucinated guesses. The opportunity now is moving from reactive data use (reviewing what happened) to predictive data use (anticipating what will happen), which is where AI creates the most compelling business value.',
      nextStep: 'Identify one business question you currently answer by looking backwards — like \'which clients are at risk of churning\' — and scope a 30-day pilot using your existing data to answer it predictively using an AI tool.',
    },
  },
  D2: {
    LOW: {
      scoreLabel: '⚠️ Leadership Not Yet Engaged',
      headline: 'AI has no owner, no agenda slot, and no budget',
      diagnosis: 'Your responses show a complete absence of the conditions that make AI initiatives succeed: AI has not appeared on your leadership agenda in any structured way, accountability for outcomes does not exist (failed initiatives simply fade away), decisions about tools and processes are made reactively when something breaks rather than by structured evaluation, there is no protected time or budget for improvement work, and there is no mechanism for team members to surface ideas for change. McKinsey\'s 2024 research across 3,600 organisations found that this combination — no ownership, no protected capacity, no evaluation process — is more reliably predictive of AI failure than any technology limitation. The technology is the easiest part of the problem.',
      nextStep: 'In your next leadership meeting, answer one question out loud: \'Who in this room owns the outcome if we start using AI and it doesn\'t deliver?\' — if nobody raises their hand, name someone before the meeting ends, give them one hour a week, and ask them to come back in two weeks with one specific use case to investigate.',
    },
    MID: {
      scoreLabel: '🔶 Strategy Emerging, Execution Patchy',
      headline: 'Awareness is there but accountability gaps are slowing progress',
      diagnosis: 'Leadership is aware of AI and has had meaningful conversations, but the execution layer is still forming — decisions about which tools to use are made inconsistently, accountability for outcomes is informal, and the time and budget to experiment is not reliably protected. This is the most common position for SMEs in 2025: interested and informed but not yet structured enough to turn interest into compounding capability. The risk is that individual experiments happen but never connect into anything systematic, and the organisation stays in permanent pilot mode.',
      nextStep: 'Assign a named AI Lead — this does not need to be a full-time role, just a person with 2–3 hours a week and explicit authority to evaluate, propose, and report on AI initiatives — and schedule a monthly 30-minute review of active and proposed experiments.',
    },
    HIGH: {
      scoreLabel: '✅ Leadership Actively Steering AI',
      headline: 'Strategic ownership and decision rigour are in place',
      diagnosis: 'Your leadership team has moved beyond awareness into active stewardship: AI appears on your agenda with concrete use cases, accountability is defined, and you have protected capacity for improvement work. This is a genuinely rare position among SMEs — BCG\'s 2024 AI Maturity study found that only 4% of companies achieve this level of leadership integration, and those companies showed 3.6x higher total shareholder returns over 5 years. Your leadership foundation means the bottlenecks will now be elsewhere — data quality, change management, or measurement rigour — rather than executive buy-in.',
      nextStep: 'Formalise your AI strategy into a one-page document: three AI objectives for the next 12 months, the owner of each, the metric that defines success, and a quarterly review date — this transforms informal alignment into institutional commitment.',
    },
  },
  D3: {
    LOW: {
      scoreLabel: '⚠️ Critical Governance Gap — Legal Exposure',
      headline: 'No rules, no controls, no safety net',
      diagnosis: 'Your responses indicate that your business has no formal AI usage policy, no controls preventing client data from entering public AI tools, and no process for detecting or responding to AI errors — meaning your business has almost certainly already experienced data exposure incidents without knowing it. This is not just a governance best practice gap: under the EU AI Act 2024 and UK ICO guidance, organisations processing personal data with AI tools have active compliance obligations right now, and the combination of no policy and no controls represents real legal exposure. This dimension acts as a hard gate in our scoring: weak governance caps your overall readiness score because scaling AI without it causes compounding risk, not compounding value.',
      nextStep: 'This week, write a single-page AI Usage Policy covering three rules: which tools are approved, what data may never be entered into public AI tools, and who to contact if something goes wrong — share it with every team member and ask them to confirm they have read it.',
    },
    MID: {
      scoreLabel: '🔶 Basic Governance in Place, Gaps Remain',
      headline: 'Policy exists but controls and response processes are incomplete',
      diagnosis: 'You have made meaningful progress: there is at least a basic written policy and some awareness of data handling risks. The gaps are in operationalisation — you have rules but not always the technical controls to enforce them, quality checking of AI outputs is informal, and your incident response if something goes wrong is reactive rather than planned. As you scale AI use, these gaps compound: a policy that people have read once is quickly forgotten, and \'we\'ll deal with it if it happens\' only works until it happens with a client.',
      nextStep: 'Set up a simple AI output review practice: for the next 30 days, ask whoever uses AI outputs for client-facing work to do a 60-second factual check before sending — log any errors in a shared document, and review them monthly to identify which tools or task types generate the most mistakes.',
    },
    HIGH: {
      scoreLabel: '✅ Governance and Risk Management Are Mature',
      headline: 'Controls, policy, and response processes are properly structured',
      diagnosis: 'Your governance posture is strong: you have an active, current AI policy, technical controls preventing unauthorised data use, a quality review process for AI outputs, and a defined incident response pathway. This puts you ahead of the large majority of SMEs, and it means you can scale AI use without dramatically increasing your risk exposure — each new tool or use case gets evaluated within an existing framework rather than treated as a novel risk each time. The next frontier is moving from reactive governance (responding when things go wrong) to proactive governance (tracking AI performance over time and continuously improving your approved toolkit).',
      nextStep: 'Create a simple quarterly AI tool review: for each approved tool, score it on output quality, data safety compliance, and team adoption — retire tools scoring poorly, and use the review to maintain a current approved list that your team can trust.',
    },
  },
  D4: {
    LOW: {
      scoreLabel: '⚠️ Team Not Yet Ready to Adopt',
      headline: 'Resistance is high and learning infrastructure is absent',
      diagnosis: 'Your responses show that your team has a history of reverting to old ways when change is introduced, there are no people in place who help colleagues adopt new tools, and no protected time for learning — the conditions that would allow AI to take root simply do not exist yet. This is not a criticism of your people: HBR\'s 2025 research into AI adoption barriers found that fear of job displacement and absence of structured support — not unwillingness to learn — are the primary causes of failed adoption. The technology is the easy part; the human conditions for adoption are what you need to build first.',
      nextStep: 'Before introducing any AI tool to your team, run a single 45-minute session where you address one question directly: \'How might AI make each person\'s job easier rather than replace it?\' — use real examples from your industry and invite the team to identify one task they personally find tedious that AI could handle.',
    },
    MID: {
      scoreLabel: '🔶 Readiness Building But Unstructured',
      headline: 'Willingness exists — structure and consistency are the gap',
      diagnosis: 'Your team is broadly open to AI — some people are already experimenting, there is interest rather than active resistance, and at least some learning has happened in recent months. The gap is that adoption depends too much on individual enthusiasm rather than structured support: without recognised champions and protected learning time, progress will be inconsistent and heavily dependent on whoever happens to be curious that month. PwC\'s 2024 research found that 74% of SMB employees feel unprepared for AI — willingness alone does not close the preparation gap.',
      nextStep: 'Name one person per team or function as an AI Champion — give them 2 hours a month of protected time, ask them to run one 30-minute tool demo per quarter, and create a simple shared channel or document where the team logs prompts and tools that have saved them time.',
    },
    HIGH: {
      scoreLabel: '✅ Team Is Ready and Engaged',
      headline: 'Adoption culture and learning infrastructure are genuinely strong',
      diagnosis: 'Your team has the conditions for AI to spread organically: they are open to change, past adoptions have gone well, champions exist who help colleagues, and learning happens regularly rather than being left to chance. This readiness is a genuine competitive advantage — McKinsey found that organisations where employees proactively adopt AI and share discoveries with each other see 2–3x faster time to value from AI investments than those where adoption must be pushed from the top. Your next challenge shifts from \'will people use it?\' to \'how do we channel that energy into the highest-value use cases?\'',
      nextStep: 'Run a structured \'AI Opportunity Sprint\' — give your team a 2-week window to each identify one task they currently do manually that they believe AI could do better, document it in a shared template, and then prioritise the top 3 by time saved × frequency for your next AI pilot.',
    },
  },
  D5: {
    LOW: {
      scoreLabel: '⚠️ Processes Are Ad-Hoc and Undocumented',
      headline: 'Work depends on people, not systems — AI cannot improve what is not defined',
      diagnosis: 'Your responses show that your business has no consistent process infrastructure: critical knowledge is entirely in people\'s heads with nothing written down, recurring problems get fixed repeatedly without ever addressing the root cause, handoffs happen by email or verbal instruction where things regularly get missed, every person does repeated tasks their own way with no shared templates, and you have no operational metrics telling you whether things are running well. This is the most common starting point for SME process maturity — and it is also the clearest explanation for why AI automation attempts fail at this stage: you cannot automate a process that has not been defined, you cannot improve a process you are not measuring, and you cannot scale work that depends entirely on a specific person being in the room.',
      nextStep: 'Pick your single most repeated process — the task your team performs most often, like client onboarding, proposal writing, or weekly reporting — and spend 90 minutes this week writing a numbered step-by-step description of exactly how it should be done from start to finish, then share it with the team and tell them this is now the standard: that one document is your entire process foundation.',
    },
    MID: {
      scoreLabel: '🔶 Some Processes Defined, Consistency Is The Gap',
      headline: 'Documentation exists but standardisation is incomplete',
      diagnosis: 'You have made real progress in process definition — some workflows are documented, shared tools are used for handoffs in at least some areas, and templates exist even if they are not always followed consistently. The gap is that process adherence depends too much on individual discipline rather than system design: when people are busy, they skip the template or do the handoff via email because it feels faster, which gradually erodes the consistency that makes automation reliable. CMMI research shows that organisations at this level typically get 40–60% of the benefit from process improvement, with the remaining gains blocked by inconsistency.',
      nextStep: 'Choose your most critical workflow and make the template non-optional for one month: tell the team the template is the process now, track completion in your shared system, and at the end of the month review what gaps or friction points need addressing — then fix those before adding AI on top.',
    },
    HIGH: {
      scoreLabel: '✅ Processes Are Defined, Measured, and Improving',
      headline: 'Process maturity is strong — AI can be layered on reliably',
      diagnosis: 'Your processes are genuinely mature: core workflows are documented and followed consistently, handoffs are managed in shared systems, recurring problems are addressed at root cause rather than patched repeatedly, and you track operational metrics that tell you whether things are running well. This is the foundation that makes AI automation reliable rather than risky — when a process is clearly defined and consistently followed, an AI layer produces consistent, auditable, improvable outputs. You are in a position where the question is not \'should we automate this?\' but \'which processes will deliver the highest return when we do?\'',
      nextStep: 'Map your top 5 most time-consuming processes against two dimensions — frequency (how often it occurs) and manual effort per occurrence — then pick the one in the top-right of that matrix (high frequency, high effort) as your first AI automation target.',
    },
  },
  D6: {
    LOW: {
      scoreLabel: '⚠️ AI Use Is Minimal or Absent',
      headline: 'AI use is absent or uncontrolled — no capability is being built',
      diagnosis: 'Your responses show that AI is either not used at all in your business, or is being used by isolated individuals with no shared knowledge, no managed access (meaning people are signing up for whatever tools they find independently, creating data handling risks), no structured experiments with defined success criteria, and no automation of any repetitive tasks. This combination — ad-hoc individual use with no institutional learning — is the pattern that produces both the lowest value and the highest risk from AI: the organisation gets none of the efficiency gains while accumulating data exposure and compliance risks from unmanaged tool usage. McKinsey\'s 2024 data shows 22% of organisations are at this stage; the fastest movers do not experiment with ten tools at once — they pick one use case, structure it properly, and build from a real result.',
      nextStep: 'This week, do two things: first, tell your team which AI tools are approved to use for work tasks (even if it is just one — ChatGPT or Microsoft Copilot — the point is to name it); second, pick the single most repetitive writing task in your business and spend 30 minutes testing that approved tool against a real example, comparing the output to your usual standard and noting what worked and what needed fixing.',
    },
    MID: {
      scoreLabel: '🔶 Individual Use Active, Team Adoption Inconsistent',
      headline: 'AI is being used but knowledge stays with individuals',
      diagnosis: 'AI tools are being used in your business — some team members are experimenting, there is growing awareness of what is possible, and at least some automation exists. The gap is that these gains are individual rather than organisational: discoveries stay with whoever made them, prompts that took an hour to develop are lost when that person is on holiday, and the business is not learning as a whole even though individuals are. Ovaledge\'s 2025 research found that \'prompt engineering capability\' — the ability of a team to systematically develop and share effective AI instructions — is one of the top differentiators between organisations that get marginal AI benefits and those that get transformational ones.',
      nextStep: 'Create a shared AI Prompt Library this week — a simple Google Doc or Notion page with three sections: the task, the prompt that works, and the time it saves — ask everyone who uses AI to add to it, and make reviewing it part of your next team meeting.',
    },
    HIGH: {
      scoreLabel: '✅ AI Is Embedded and Systematically Improving',
      headline: 'AI use is structured, shared, and experiment-driven',
      diagnosis: 'Your business has genuine AI capability: tools are used across the team in defined workflows, knowledge about what works is captured and shared, tool access is managed, and you run experiments with real success criteria rather than just trying things informally. This is a strong position — BCG\'s 2024 research found that organisations with systematic AI adoption practices see 3x higher value realisation from AI investment than those relying on individual initiative. The next step is moving from task-level AI (individual tasks automated) to workflow-level AI (entire workflows redesigned around AI-native processes).',
      nextStep: 'Identify one end-to-end workflow — not just a single task but a complete process from trigger to output — and redesign it from scratch assuming AI is available at every step: map out what a human still needs to do, what AI handles, and what the new workflow looks like, then pilot it for 30 days.',
    },
  },
  D7: {
    LOW: {
      scoreLabel: '🔶 Tech Stack Needs Foundational Work',
      headline: 'Disconnected systems and weak controls will limit AI use cases',
      diagnosis: 'Your core systems do not share data — information is re-entered manually between tools, reporting depends on one person, access controls are minimal, and your stack has significant on-premise or device-specific components. It is worth noting that technology is the lowest-weighted dimension in this assessment (8%) because it is the most easily fixed: you can buy better tools, migrate to cloud, and connect systems in weeks — none of which requires organisational culture change. That said, disconnected systems do limit which AI use cases are practically feasible: AI that automates a workflow needs to read from and write to your systems, and that requires at least basic connectivity.',
      nextStep: 'Identify the single most painful manual data re-entry step in your operations — the place where someone copies information from one tool into another most frequently — and investigate whether a native integration or a simple automation tool like Zapier or Make can eliminate it within two weeks.',
    },
    MID: {
      scoreLabel: '🔶 Tech Stack Is Functional, Gaps Are Manageable',
      headline: 'Core connectivity exists but data access and controls are inconsistent',
      diagnosis: 'You have working integrations between some key systems, most of your stack is cloud-based, and dashboards exist even if they are not always self-service. The gaps are specific rather than systemic: some manual bridging remains, tool ownership is informal in places, and access controls are not consistently applied. These are solvable problems — and importantly, they are lower priority than data quality, governance, and people readiness, which are harder to fix and have more impact on AI outcomes.',
      nextStep: 'Audit your current tool stack in 30 minutes: list every tool the business pays for, who owns it internally, and whether it has an active integration with your other core systems — remove or replace any tool with no internal owner, as unowned tools are your most common source of data fragmentation.',
    },
    HIGH: {
      scoreLabel: '✅ Tech Infrastructure Is Ready for AI',
      headline: 'Connected, cloud-based stack with clear ownership and controls',
      diagnosis: 'Your technology infrastructure is genuinely AI-ready: systems are connected and share data automatically, reporting is self-service, tool ownership is clear, access controls are properly managed, and your stack is fully cloud-based. This means the technical barriers to deploying AI tools are low — you can connect AI to your data, automate workflows across systems, and deploy new tools without significant infrastructure work. Remember that tech readiness (8% of your total score) is the easiest dimension to improve but not the most impactful — your time is better spent on dimensions with higher weights and lower scores.',
      nextStep: 'Map your current system integrations visually — which tools connect to which, and where data flows automatically versus manually — then identify one AI tool from your approved list that could plug directly into an existing integration to add value without requiring new infrastructure.',
    },
  },
  D8: {
    LOW: {
      scoreLabel: '⚠️ No Measurement Culture Yet',
      headline: 'Without baselines, you cannot prove — or improve — AI\'s value',
      diagnosis: 'Your responses show that your business does not currently measure the impact of improvements: success is assessed by feeling rather than data, baselines are not established before changes are made, and AI pilots are not evaluated against pre-defined criteria. Ovaledge\'s 2025 research found that 45% of organisations struggle to prove AI ROI specifically because they never measured the baseline they were improving from. This is a critical gap not because measurement is intrinsically complex, but because without it you will spend money on AI tools, see some subjective benefit, and be unable to justify continued investment or identify what is actually working.',
      nextStep: 'Before your next process change or AI trial, spend 20 minutes measuring the current state: count how many times the task occurs per week, time how long it takes a person to complete it once, and write those two numbers down — those are your baseline, and they are all you need to calculate ROI six months later.',
    },
    MID: {
      scoreLabel: '🔶 Some Measurement Exists, Not Yet Systematic',
      headline: 'You track some outcomes but baselining and pilot gates are inconsistent',
      diagnosis: 'You have started building measurement practices: some metrics are tracked, success is not purely anecdotal, and at least occasional baselining happens before changes. The gap is consistency — pilots sometimes have clear criteria and sometimes don\'t, prioritisation of AI use cases is partly instinct and partly structured, and scale versus stop decisions are not made against pre-defined thresholds. BCG found that organisations with systematic measurement practices are 3x more likely to scale an AI pilot to production than those that evaluate informally, because systematic measurement surfaces the real barriers earlier when they are cheaper to fix.',
      nextStep: 'For your current or next AI initiative, write a one-paragraph \'pilot brief\' before starting — state the problem, the metric you will use to measure success, the baseline value today, and the threshold that will tell you whether to scale or stop — make this the non-negotiable entry ticket for any new AI experiment.',
    },
    HIGH: {
      scoreLabel: '✅ ROI Discipline Is Strong and Systematic',
      headline: 'Measurement, baselining, and pilot governance are genuinely mature',
      diagnosis: 'Your business has developed something genuinely rare: disciplined ROI measurement for improvement initiatives. You baseline before changing, define success criteria before starting, and make scale versus stop decisions against evidence rather than enthusiasm. BCG\'s 2024 research found that only 12% of organisations reach this level of AI measurement maturity, and those organisations achieve an average of 2.8x higher value realisation from AI investments than the median. This capability means your AI investments will compound — each pilot produces learnings that inform the next one, and the organisation continuously improves its ability to identify and capture value from AI.',
      nextStep: 'Build a simple AI ROI register — a shared document listing every AI initiative with its baseline metric, its target, its current performance, and its status (active pilot / scaled / stopped) — review it quarterly and use it to build the business case for continued AI investment with concrete numbers.',
    },
  },
};


// Get the diagnostic level based on dimension score
export function getDiagnosticLevel(score: number): DiagnosticLevel {
  if (score <= 4.5) return 'LOW';
  if (score <= 7.4) return 'MID';
  return 'HIGH';
}

// Get the full diagnostic block for a specific dimension and score
export function getDiagnosticBlock(dimId: DimensionId, score: number): DiagnosticBlock {
  const level = getDiagnosticLevel(score);
  return diagnosticBlocks[dimId][level];
}

// Legacy compat: get the diagnostic text (diagnosis paragraph) for a dimension and score
export function getDiagnosticText(dimId: DimensionId, score: number): string {
  return getDiagnosticBlock(dimId, score).diagnosis;
}
