// lib/config/questions.config.ts
// Auto-generated from AiGENiQ_Question_Bank_v3.1.xlsx
// DO NOT EDIT MANUALLY — re-run generate_app_code.py to regenerate

import { Question, ContextQuestion, Sector, DimensionId } from '../../types';

// ─── CONTEXT QUESTIONS (5 Unscored — Asked First) ───
export const contextQuestions: ContextQuestion[] = [
  {
    id: 'C-Q1',
    order: 1,
    text: 'Which sector best describes your business?',
    options: ['Professional Services (legal, accountancy, HR, finance, consultancy)', 'Creative & Agency (marketing, design, PR, content, media)', 'Technology & Software (SaaS, IT services, digital agency, tech startup)', 'Trade & Field Services (construction, engineering, maintenance, logistics)', 'Retail & Hospitality (ecommerce, physical retail, restaurants, hotels)', 'Health & Wellbeing (clinics, dentists, physios, wellness, care homes)', 'Other'],
    isMultiSelect: false,
  },
  {
    id: 'C-Q2',
    order: 2,
    text: 'How many people work in your business (including part-time and contractors)?',
    options: ['Solo / just me', '2–9', '10–49', '50–249', '250+'],
    isMultiSelect: false,
  },
  {
    id: 'C-Q3',
    order: 3,
    text: 'Which AI tools (if any) does your team currently use? (Select all that apply)',
    options: ['ChatGPT / OpenAI', 'Microsoft Copilot', 'Google Gemini / Workspace AI', 'Notion AI', 'Midjourney / DALL-E', 'GitHub Copilot', 'Internal / bespoke AI tools', 'None', 'Other'],
    isMultiSelect: true,
  },
  {
    id: 'C-Q4',
    order: 4,
    text: 'What business areas are you most hoping AI can help with? (Select up to 3)',
    options: ['Sales & business development', 'Operations & delivery', 'Finance & reporting', 'HR & people', 'Customer service', 'Marketing & content', 'Product or service development', 'Data & analytics', 'Legal & compliance', 'Other'],
    isMultiSelect: true,
    maxSelections: 3,
  },
  {
    id: 'C-Q5',
    order: 5,
    text: 'Who is completing this assessment?',
    options: ['Founder / CEO / MD', 'Operations or delivery lead', 'IT or technology lead', 'HR or people lead', 'External consultant or advisor', 'Other'],
    isMultiSelect: false,
  },
];

// ─── UNIVERSAL QUESTIONS (40 Scored — 8 Dimensions × 5 Questions) ───
export const universalQuestions: Question[] = [
  {
    id: 'D1-Q1',
    dimensionId: 'D1' as DimensionId,
    dimensionName: 'Data & Knowledge Foundations',
    order: 1,
    text: 'When a team member leaves your business, what happens to the knowledge, contacts, and files they owned?',
    options: {
      A: 'It\'s mostly in their head or personal files; we scramble to recover it',
      B: 'Some things are findable; others are lost or need to be rebuilt',
      C: 'Most key info is in shared systems, but takes effort to piece together',
      D: 'Clear handover process exists; successor can pick up from day one',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D1-Q2', 'D1-Q3'],
    autoScoreOnSkip: 0.5,
    isHardGate: true,
  },
  {
    id: 'D1-Q2',
    dimensionId: 'D1' as DimensionId,
    dimensionName: 'Data & Knowledge Foundations',
    order: 2,
    text: 'If a new employee needed to find your most current customer list and pricing today, what would they actually do?',
    options: {
      A: 'Ask someone verbally; no single place to look',
      B: 'Check several tools or folders — likely finding conflicting versions',
      C: 'Go to one main system, though it may not always be fully up to date',
      D: 'Access a single, maintained source of truth they can trust immediately',
    },
    isBranchChild: true,
    isHardGate: true,
  },
  {
    id: 'D1-Q3',
    dimensionId: 'D1' as DimensionId,
    dimensionName: 'Data & Knowledge Foundations',
    order: 3,
    text: 'When you make a business decision (pricing, hiring, which client to prioritise), what is it typically based on?',
    options: {
      A: 'Experience and gut feel; we don\'t look at data',
      B: 'Occasional spreadsheets or reports, but nothing consistent',
      C: 'Regular reports or dashboards, though not always trusted by the team',
      D: 'Defined metrics reviewed regularly; data actively shapes decisions',
    },
    isBranchChild: true,
    isHardGate: true,
  },
  {
    id: 'D1-Q4',
    dimensionId: 'D1' as DimensionId,
    dimensionName: 'Data & Knowledge Foundations',
    order: 4,
    text: 'How do you capture and reuse knowledge from completed work — proposals won, projects delivered, problems solved?',
    options: {
      A: 'We don\'t; it lives with whoever did it',
      B: 'Some people save things; no consistent format or location',
      C: 'Shared folder or wiki exists, though not always maintained',
      D: 'Structured knowledge base the team actively adds to and searches',
    },
    isHardGate: true,
  },
  {
    id: 'D1-Q5',
    dimensionId: 'D1' as DimensionId,
    dimensionName: 'Data & Knowledge Foundations',
    order: 5,
    text: 'If you wanted to analyse which types of customers are most profitable, how long would it realistically take?',
    options: {
      A: 'Weeks — or we simply couldn\'t do it without a big manual exercise',
      B: 'Days — data exists but needs cleaning and combining from several places',
      C: 'Hours — mostly accessible but requires some manual preparation',
      D: 'Minutes — defined reports exist; data is clean and ready to query',
    },
    isHardGate: true,
  },
  {
    id: 'D2-Q1',
    dimensionId: 'D2' as DimensionId,
    dimensionName: 'Leadership & Strategy',
    order: 6,
    text: 'In the last 3 months, has your leadership team discussed a specific AI initiative — not AI in general, but a concrete use case — in a formal meeting?',
    options: {
      A: 'No; AI has not come up in any structured way',
      B: 'Mentioned briefly but no follow-through or owner assigned',
      C: 'Yes, discussed at least once with a named next step',
      D: 'Yes, with a defined owner, timeline, and it is being tracked',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D2-Q2'],
    autoScoreOnSkip: 0.5,
    isSoftGate: true,
  },
  {
    id: 'D2-Q2',
    dimensionId: 'D2' as DimensionId,
    dimensionName: 'Leadership & Strategy',
    order: 7,
    text: 'Who is accountable if an AI initiative in your business fails to deliver results?',
    options: {
      A: 'Nobody — it would just be noted as \'didn\'t work out\'',
      B: 'Whoever ran it informally; not a formal accountability',
      C: 'A named person with responsibility, though their authority is limited',
      D: 'Clear owner with defined scope, authority, and reporting to leadership',
    },
    isBranchChild: true,
    isSoftGate: true,
  },
  {
    id: 'D2-Q3',
    dimensionId: 'D2' as DimensionId,
    dimensionName: 'Leadership & Strategy',
    order: 8,
    text: 'When your business last evaluated a new operational tool or process change, how was the decision made?',
    options: {
      A: 'Someone tried it and it stuck, or it faded — no formal process',
      B: 'Leader made a call based on recommendation; no structured evaluation',
      C: 'Some comparison against goals, cost, and feasibility before deciding',
      D: 'Structured evaluation: criteria set, options compared, risks considered, decision documented',
    },
    isSoftGate: true,
  },
  {
    id: 'D2-Q4',
    dimensionId: 'D2' as DimensionId,
    dimensionName: 'Leadership & Strategy',
    order: 9,
    text: 'How does your business currently allocate time or budget for exploring improvements or new technology?',
    options: {
      A: 'It doesn\'t; improvements happen reactively when something breaks',
      B: 'Occasionally when someone pushes it — no regular cadence',
      C: 'Planned capacity exists (e.g. quarterly review, small innovation budget)',
      D: 'Dedicated time and budget protected from day-to-day operations',
    },
    isSoftGate: true,
  },
  {
    id: 'D2-Q5',
    dimensionId: 'D2' as DimensionId,
    dimensionName: 'Leadership & Strategy',
    order: 10,
    text: 'If a frontline team member identified a time-wasting process and proposed an AI-assisted fix, what would most likely happen?',
    options: {
      A: 'Nothing — no clear path to raise it or get it evaluated',
      B: 'Noted but rarely acted on; depends on whether the right person heard it',
      C: 'There\'s a way to flag it, and it would likely get reviewed',
      D: 'Clear submission route, regular review cycle, and feedback given on every idea',
    },
    isSoftGate: true,
  },
  {
    id: 'D3-Q1',
    dimensionId: 'D3' as DimensionId,
    dimensionName: 'Governance & Risk',
    order: 11,
    text: 'If an employee pasted a client\'s personal data into ChatGPT or a similar public AI tool today, would anyone in your business know?',
    options: {
      A: 'No — there are no controls; this has probably already happened',
      B: 'Unlikely to be caught; we\'ve mentioned concerns but nothing is in place',
      C: 'We have a policy against it, though technical controls don\'t exist yet',
      D: 'Yes — approved tool list, data classification rules, and access controls active',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D3-Q2', 'D3-Q3'],
    autoScoreOnSkip: 0.5,
    isHardGate: true,
  },
  {
    id: 'D3-Q2',
    dimensionId: 'D3' as DimensionId,
    dimensionName: 'Governance & Risk',
    order: 12,
    text: 'Your business starts using an AI tool that consistently produces wrong outputs for one type of task. How would you find out?',
    options: {
      A: 'A client would complain or we\'d notice significant damage — no proactive check',
      B: 'Someone might flag it informally, but it\'s not systematic',
      C: 'We do spot-checks on AI outputs; someone has informal responsibility',
      D: 'Defined quality review process; outputs checked against criteria; issues logged',
    },
    isBranchChild: true,
    isHardGate: true,
  },
  {
    id: 'D3-Q3',
    dimensionId: 'D3' as DimensionId,
    dimensionName: 'Governance & Risk',
    order: 13,
    text: 'Does your business have a written AI usage policy that employees have actually seen?',
    options: {
      A: 'No policy exists',
      B: 'Informal guidance was shared once but not formalised or updated',
      C: 'Basic written policy exists and was communicated, though not regularly revisited',
      D: 'Current policy, version-controlled, communicated at onboarding and reviewed annually',
    },
    isBranchChild: true,
    isHardGate: true,
  },
  {
    id: 'D3-Q4',
    dimensionId: 'D3' as DimensionId,
    dimensionName: 'Governance & Risk',
    order: 14,
    text: 'Before your business starts using a new AI tool in a client-facing or sensitive internal process, what assessment happens?',
    options: {
      A: 'None — we try it and see what happens',
      B: 'Someone looks at the vendor website and makes a call',
      C: 'Informal checklist covering obvious risks (data handling, cost, reliability)',
      D: 'Structured risk assessment: data classification, vendor due diligence, compliance check, sign-off',
    },
    isHardGate: true,
  },
  {
    id: 'D3-Q5',
    dimensionId: 'D3' as DimensionId,
    dimensionName: 'Governance & Risk',
    order: 15,
    text: 'If an AI output caused a material error — a wrong recommendation to a client or a compliance breach — what would happen next?',
    options: {
      A: 'No process; we\'d improvise and hope it didn\'t escalate',
      B: 'Deal with the immediate fallout; no defined learning or prevention process',
      C: 'Defined reporting path; incident logged; root cause identified',
      D: 'Incident response plan, mandatory logging, corrective action tracked, policy updated',
    },
    isHardGate: true,
  },
  {
    id: 'D4-Q1',
    dimensionId: 'D4' as DimensionId,
    dimensionName: 'People & Change Readiness',
    order: 16,
    text: 'Think about the last time your team was asked to change how they work — a new tool, new process, new system. What happened in the first 4 weeks?',
    options: {
      A: 'Most people reverted to the old way; adoption was minimal',
      B: 'Mixed — some adopted it, others quietly didn\'t',
      C: 'Mostly adopted, though it took more effort and time than expected',
      D: 'Smooth adoption with structured rollout, clear communication, and support',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D4-Q2'],
    autoScoreOnSkip: 0.5,
  },
  {
    id: 'D4-Q2',
    dimensionId: 'D4' as DimensionId,
    dimensionName: 'People & Change Readiness',
    order: 17,
    text: 'Do you have a person in your team — at any level — who actively champions new tools and helps colleagues get comfortable with them?',
    options: {
      A: 'No; everyone is too stretched to take that on',
      B: 'Someone informally plays this role but it\'s not recognised or resourced',
      C: 'Yes, a named person or two who help others and run informal sessions',
      D: 'Recognised AI champions per function with time allocated and a regular rhythm',
    },
    isBranchChild: true,
  },
  {
    id: 'D4-Q3',
    dimensionId: 'D4' as DimensionId,
    dimensionName: 'People & Change Readiness',
    order: 18,
    text: 'In the last 90 days, what AI-related learning has happened in your business?',
    options: {
      A: 'Nothing structured; people learn on their own if curious',
      B: 'One or two people explored tools independently; nothing team-wide',
      C: 'At least one team session or walkthrough — informal but intentional',
      D: 'Structured programme: role-specific training, defined outcomes, tracked',
    },
  },
  {
    id: 'D4-Q4',
    dimensionId: 'D4' as DimensionId,
    dimensionName: 'People & Change Readiness',
    order: 19,
    text: 'When you mention AI or automation to your team, what is the most common reaction you observe?',
    options: {
      A: 'Anxiety or active resistance — concern about job security',
      B: 'Polite interest but no real engagement or curiosity',
      C: 'Generally open; some enthusiasm, though people want guidance',
      D: 'Team actively seeks out AI tools and shares discoveries with each other',
    },
  },
  {
    id: 'D4-Q5',
    dimensionId: 'D4' as DimensionId,
    dimensionName: 'People & Change Readiness',
    order: 20,
    text: 'How much protected time does your team realistically have for learning and process improvement — not firefighting?',
    options: {
      A: 'None; everyone is fully absorbed in delivery',
      B: 'Less than 1 hour per month per person on average',
      C: '1–3 hours per month — some protected but not consistent',
      D: 'Regular protected time (half-day or more per month) built into the schedule',
    },
  },
  {
    id: 'D5-Q1',
    dimensionId: 'D5' as DimensionId,
    dimensionName: 'Process Maturity',
    order: 21,
    text: 'If your most experienced person left tomorrow, how much of what they do is written down somewhere that others could follow?',
    options: {
      A: 'Almost none — it\'s entirely in their head',
      B: 'Some fragments exist but incomplete and hard to find',
      C: 'Key workflows are documented, though not always up to date',
      D: 'Core processes documented, version-controlled, and regularly reviewed',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D5-Q2'],
    autoScoreOnSkip: 0.5,
  },
  {
    id: 'D5-Q2',
    dimensionId: 'D5' as DimensionId,
    dimensionName: 'Process Maturity',
    order: 22,
    text: 'When the same problem keeps appearing in your operations — a recurring delay, a repeated error — what typically happens?',
    options: {
      A: 'We fix it each time it occurs but don\'t address the root cause',
      B: 'Someone notes it but there\'s no regular forum to address it',
      C: 'Periodic review meetings where recurring issues get discussed and actioned',
      D: 'Continuous improvement cadence: issues logged, root causes analysed, fixes tracked',
    },
    isBranchChild: true,
  },
  {
    id: 'D5-Q3',
    dimensionId: 'D5' as DimensionId,
    dimensionName: 'Process Maturity',
    order: 23,
    text: 'How do handoffs work in your business — when work moves between people, teams, or stages?',
    options: {
      A: 'Email or verbal; things get missed or duplicated regularly',
      B: 'Mostly email with occasional spreadsheet tracking; gaps are common',
      C: 'A shared tool (project management, CRM) is used, though not consistently',
      D: 'Defined handoff protocol in a shared system; ownership is always clear',
    },
  },
  {
    id: 'D5-Q4',
    dimensionId: 'D5' as DimensionId,
    dimensionName: 'Process Maturity',
    order: 24,
    text: 'Do you use standard templates, checklists, or playbooks for work your team does repeatedly?',
    options: {
      A: 'No; each person does it their own way',
      B: 'Some people have their own templates; nothing shared or maintained',
      C: 'Shared templates exist for key tasks; not always used consistently',
      D: 'Version-controlled templates for core workflows; improvement suggestions welcome',
    },
  },
  {
    id: 'D5-Q5',
    dimensionId: 'D5' as DimensionId,
    dimensionName: 'Process Maturity',
    order: 25,
    text: 'Can you name 3 metrics that tell you whether your core operations are running well this week — without looking them up?',
    options: {
      A: 'No; we don\'t track operational metrics consistently',
      B: 'We track revenue/sales but not operational delivery metrics',
      C: 'Yes, 2–3 metrics tracked regularly, though not always acted on',
      D: 'Dashboard of operational KPIs reviewed weekly with clear owners and thresholds',
    },
  },
  {
    id: 'D6-Q1',
    dimensionId: 'D6' as DimensionId,
    dimensionName: 'AI Usage & Adoption',
    order: 26,
    text: 'Which best describes how AI tools are used across your team right now?',
    options: {
      A: 'Not used, or only by one person occasionally',
      B: 'A few individuals use AI tools informally in their own work',
      C: 'Multiple team members use AI for specific tasks; some sharing of what works',
      D: 'AI is embedded in defined workflows; team knows what tools to use and when',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D6-Q2', 'D6-Q3'],
    autoScoreOnSkip: 0.5,
  },
  {
    id: 'D6-Q2',
    dimensionId: 'D6' as DimensionId,
    dimensionName: 'AI Usage & Adoption',
    order: 27,
    text: 'When someone in your team finds a useful AI tool or prompt, what happens to that knowledge?',
    options: {
      A: 'It stays with them; others don\'t find out unless they mention it',
      B: 'Shared in a chat or email at the time, then forgotten',
      C: 'Goes into a shared folder, doc, or channel others can access',
      D: 'Maintained library of prompts and playbooks, regularly updated and versioned',
    },
    isBranchChild: true,
  },
  {
    id: 'D6-Q3',
    dimensionId: 'D6' as DimensionId,
    dimensionName: 'AI Usage & Adoption',
    order: 28,
    text: 'How do people in your business get access to AI tools?',
    options: {
      A: 'Everyone signs up independently for whatever they want',
      B: 'Informal; some tools are used but nobody tracks what or by whom',
      C: 'An approved list or preferred tools exist; onboarding is informal',
      D: 'Managed onboarding to approved tools; usage tracked; licences reviewed periodically',
    },
    isBranchChild: true,
  },
  {
    id: 'D6-Q4',
    dimensionId: 'D6' as DimensionId,
    dimensionName: 'AI Usage & Adoption',
    order: 29,
    text: 'Have you run any structured experiment with AI — even a small one — where you defined what success looked like before starting?',
    options: {
      A: 'No; any AI use has been exploratory with no success criteria',
      B: 'We\'ve tried things but measured success informally (\'it seemed faster\')',
      C: 'At least once: defined goal, ran the test, compared to baseline',
      D: 'Standard practice: every AI initiative has hypothesis, metrics, and review date',
    },
  },
  {
    id: 'D6-Q5',
    dimensionId: 'D6' as DimensionId,
    dimensionName: 'AI Usage & Adoption',
    order: 30,
    text: 'Do you use any tools to automate repetitive tasks — routing emails, scheduling, updating records, generating reports?',
    options: {
      A: 'No automation; everything is manual',
      B: 'One or two personal automations (individual setup, not team-wide)',
      C: 'Team-level automations exist for specific tasks; documented',
      D: 'End-to-end automated workflows with monitoring, error alerts, and regular reviews',
    },
  },
  {
    id: 'D7-Q1',
    dimensionId: 'D7' as DimensionId,
    dimensionName: 'Tech & Integration',
    order: 31,
    text: 'How well do your core business systems talk to each other — CRM, finance tool, email platform, and operational software?',
    options: {
      A: 'They don\'t; data is re-entered manually between them',
      B: 'Occasional manual exports/imports; mostly disconnected',
      C: 'Some direct integrations; still some manual bridging',
      D: 'API-connected or iPaaS-managed; data flows automatically between key systems',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D7-Q2'],
    autoScoreOnSkip: 0.5,
  },
  {
    id: 'D7-Q2',
    dimensionId: 'D7' as DimensionId,
    dimensionName: 'Tech & Integration',
    order: 32,
    text: 'How does your team access data and reporting — can most people get what they need without asking a specific person?',
    options: {
      A: 'Reporting is done manually by one person when requested',
      B: 'Basic reports exist but only specific people know how to run them',
      C: 'Shared dashboards available; most people can access relevant data',
      D: 'Self-service dashboards per role; real-time data with alerts for key thresholds',
    },
    isBranchChild: true,
  },
  {
    id: 'D7-Q3',
    dimensionId: 'D7' as DimensionId,
    dimensionName: 'Tech & Integration',
    order: 33,
    text: 'When a new tool or system is introduced, who owns the implementation and ongoing maintenance?',
    options: {
      A: 'Nobody; it gets set up once and then nobody owns it',
      B: 'Vendor handles it; internally nobody has clear responsibility',
      C: 'A power user or team lead takes informal ownership',
      D: 'Named internal owner with a repeatable onboarding and change process',
    },
  },
  {
    id: 'D7-Q4',
    dimensionId: 'D7' as DimensionId,
    dimensionName: 'Tech & Integration',
    order: 34,
    text: 'How would you describe the security and access controls on your business tools — who can access what?',
    options: {
      A: 'Everyone has access to everything; no formal controls',
      B: 'Basic controls (passwords, shared logins) but not role-based',
      C: 'Role-based access for most critical systems; reviewed occasionally',
      D: 'Managed access control, MFA on critical tools, access reviewed regularly',
    },
  },
  {
    id: 'D7-Q5',
    dimensionId: 'D7' as DimensionId,
    dimensionName: 'Tech & Integration',
    order: 35,
    text: 'Are your core business tools cloud-based and accessible from anywhere, or tied to specific devices or locations?',
    options: {
      A: 'Mostly on-premise or device-specific; limited remote access',
      B: 'Mixed; some cloud, some local — remote access is inconsistent',
      C: 'Mostly cloud-based; occasional friction with older systems',
      D: 'Fully cloud-based, standardised stack, accessible from any device',
    },
  },
  {
    id: 'D8-Q1',
    dimensionId: 'D8' as DimensionId,
    dimensionName: 'Value & ROI Discipline',
    order: 36,
    text: 'When your business spends time or money on a process improvement or new tool, how do you know 6 months later if it worked?',
    options: {
      A: 'We don\'t measure it; success is a feeling, not a number',
      B: 'Anecdotal — \'it seems better\' based on informal feedback',
      C: 'We track 1–2 metrics; comparison to before is rough but exists',
      D: 'Baseline measured before; outcomes tracked against it; reviewed at a set date',
    },
    isBranchParent: true,
    branchTrigger: 'A',
    childQuestions: ['D8-Q2'],
    autoScoreOnSkip: 0.5,
  },
  {
    id: 'D8-Q2',
    dimensionId: 'D8' as DimensionId,
    dimensionName: 'Value & ROI Discipline',
    order: 37,
    text: 'Have you ever tracked the time your team spends on a specific task before changing how it works?',
    options: {
      A: 'No; we\'ve never baselined time or cost for a process before changing it',
      B: 'Rough estimates used occasionally, but not rigorously',
      C: 'At least once: timed the current process before proposing a change',
      D: 'Standard practice: baseline established before any process change or pilot',
    },
    isBranchChild: true,
  },
  {
    id: 'D8-Q3',
    dimensionId: 'D8' as DimensionId,
    dimensionName: 'Value & ROI Discipline',
    order: 38,
    text: 'Before starting an AI pilot, does your business define what \'success\' looks like in measurable terms — before the pilot begins?',
    options: {
      A: 'No; we see what happens and decide after',
      B: 'Vague goal (\'save time\') but nothing quantified',
      C: 'At least one metric defined upfront, though comparison is informal',
      D: 'Defined hypothesis, target metrics, timeline, and review gate before every pilot',
    },
  },
  {
    id: 'D8-Q4',
    dimensionId: 'D8' as DimensionId,
    dimensionName: 'Value & ROI Discipline',
    order: 39,
    text: 'How does your business prioritise which processes or problems to target with AI first?',
    options: {
      A: 'Whoever suggests it loudest, or whatever tool someone discovered',
      B: 'Gut feel about where the biggest pain is',
      C: 'Informal scoring: time wasted, frequency, feasibility — but not documented',
      D: 'Structured prioritisation: value vs. feasibility matrix, reviewed by a cross-functional group',
    },
  },
  {
    id: 'D8-Q5',
    dimensionId: 'D8' as DimensionId,
    dimensionName: 'Value & ROI Discipline',
    order: 40,
    text: 'After completing an AI pilot, what happens next — how does your business decide whether to scale, stop, or adjust?',
    options: {
      A: 'It either keeps running informally or gets abandoned — no formal review',
      B: 'Someone makes a call based on whether it felt useful',
      C: 'Reviewed against the original goal; decision made with clear rationale',
      D: 'Formal gate review: outcomes vs. hypothesis, documented decision, scaling playbook or shutdown log',
    },
  },
];

// ─── SECTOR OVERRIDES ───
// Each sector has 6-8 questions that REPLACE specific universal questions.
// Same Q-ID slot, same scoring (A=0, B=1.5, C=3, D=4). Only text and options change.
export const sectorOverrides: Partial<Record<Sector, Question[]>> = {
  professional_services: [
    {
      id: 'D1-Q2',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 2,
      text: 'How do you currently manage client data — storage, access, retention, and deletion?',
      options: {
        A: 'No documented policy; data is wherever it ended up',
        B: 'We follow GDPR/legal minimums but have no internal policy beyond that',
        C: 'Documented data handling policy with a named owner',
        D: 'Active governance: policy, owner, regular reviews, and staff training',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D3-Q1',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 11,
      text: 'Has your firm assessed which AI tools are permissible under your professional body guidelines (SRA, ICAEW, FCA, etc.)?',
      options: {
        A: 'No — we haven\'t looked at this through a regulatory lens',
        B: 'Vaguely aware there may be rules but haven\'t investigated formally',
        C: 'Reviewed guidance and briefed leadership on key constraints',
        D: 'Actively monitoring regulatory guidance and have a compliant tool list',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D3-Q2', 'D3-Q3'],
      autoScoreOnSkip: 0.5,
      isHardGate: true,
    },
    {
      id: 'D3-Q4',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 14,
      text: 'Do your client engagement letters or contracts address the use of AI tools in delivering their work?',
      options: {
        A: 'No — AI use in client work is not addressed in our agreements',
        B: 'Not explicitly — we rely on general terms covering third-party tools',
        C: 'AI mentioned in some newer contracts but not consistently across all clients',
        D: 'All client agreements include explicit AI usage terms, client consent, and data handling clauses',
      },
      isHardGate: true,
    },
    {
      id: 'D3-Q5',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 15,
      text: 'Do you disclose to clients when AI has been used in producing their advice, report, or deliverable?',
      options: {
        A: 'No — AI use is not disclosed',
        B: 'Informally sometimes — no consistent policy',
        C: 'We have an internal guideline but it\'s not enforced consistently',
        D: 'Always disclosed; policy documented, clients briefed, and transparency is part of our standard process',
      },
      isHardGate: true,
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'Where in your firm is AI currently being used — client delivery, back-office, or both?',
      options: {
        A: 'Not used in any structured way',
        B: 'Individuals experimenting personally — not connected to client or firm work',
        C: 'Back-office use only (drafting, scheduling, research) — not in client-facing work',
        D: 'Both back-office and defined client-facing workflows, with clear governance on each',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q4',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 29,
      text: 'When AI is used to support a client recommendation or document, is the output reviewed by a qualified professional before delivery?',
      options: {
        A: 'No formal review process — output is used as generated',
        B: 'Reviewer is aware it was AI-assisted but no specific check protocol exists',
        C: 'Outputs are checked but review process is informal and individual-dependent',
        D: 'Mandatory human review by qualified professional; documented sign-off before any AI-assisted client deliverable',
      },
    },
    {
      id: 'D2-Q5',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 10,
      text: 'Does your leadership have a position on AI that distinguishes between administrative AI use and AI in professional judgement or advice?',
      options: {
        A: 'No distinction made — AI is AI',
        B: 'Vaguely understood but not articulated as policy',
        C: 'Discussed and informally agreed; not yet formalised',
        D: 'Documented policy distinguishing administrative AI from AI in professional judgement, with different governance for each',
      },
      isSoftGate: true,
    },
    {
      id: 'D4-Q3',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 18,
      text: 'Have any staff received formal training on AI tools that are approved for use in your firm?',
      options: {
        A: 'No formal training; people use tools at their own discretion',
        B: 'Informal guidance shared once; no structured training',
        C: 'At least one team training session on approved tools has taken place',
        D: 'Role-specific AI training programme; approved tool proficiency tracked; refreshed annually',
      },
    },
  ],
  creative_agency: [
    {
      id: 'D1-Q2',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 2,
      text: 'Do you have a system for storing and reusing prompts, creative briefs, or AI-generated assets across your team?',
      options: {
        A: 'No — prompts and outputs live with whoever created them',
        B: 'Some people save their own prompts; nothing shared or organised',
        C: 'A shared folder or channel exists but isn\'t consistently maintained',
        D: 'Maintained prompt and asset library, regularly updated, with version history',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D3-Q1',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 11,
      text: 'Do your client contracts address ownership of AI-generated creative work — who owns the output?',
      options: {
        A: 'No — our contracts don\'t mention AI-generated content',
        B: 'We rely on general IP clauses; AI isn\'t explicitly addressed',
        C: 'Some newer contracts reference AI; legacy contracts don\'t',
        D: 'All client agreements include explicit AI-generated content ownership clauses, reviewed by legal',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D3-Q2', 'D3-Q3'],
      autoScoreOnSkip: 0.5,
      isHardGate: true,
    },
    {
      id: 'D3-Q4',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 14,
      text: 'Do you disclose to clients when AI has been used to generate or significantly assist creative deliverables?',
      options: {
        A: 'No — AI use is not disclosed',
        B: 'Informally sometimes — no consistent policy or wording',
        C: 'Disclosure policy exists but not enforced consistently across all client relationships',
        D: 'Always disclosed; standard wording in contracts and briefs; clients are briefed at project start',
      },
      isHardGate: true,
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'How embedded are AI tools in your creative production and client delivery workflows right now?',
      options: {
        A: 'Not used, or only by one person experimenting',
        B: 'A few individuals use AI tools for their own work; not coordinated',
        C: 'Multiple team members use AI in delivery; some shared practices and guidelines',
        D: 'AI is integrated into defined production workflows with quality checkpoints and shared playbooks',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q4',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 29,
      text: 'Do you have a quality-checking process for AI-generated creative output before it goes to clients?',
      options: {
        A: 'No — AI output is used as delivered with standard creative review only',
        B: 'Informally — the person who prompted it reviews it, no defined criteria',
        C: 'Some guidelines exist for what to check; applied inconsistently',
        D: 'Defined QC protocol for AI-generated work: accuracy, brand compliance, bias check, client brief alignment — documented',
      },
    },
    {
      id: 'D2-Q5',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 10,
      text: 'Does your agency have a stated position on AI that you communicate to prospective clients?',
      options: {
        A: 'No — we don\'t have a stated AI position',
        B: 'We mention it informally but have no consistent messaging',
        C: 'Internal position exists but hasn\'t been packaged as a client-facing statement',
        D: 'Clear AI position in our credentials deck, pitch process, and website — used as a competitive differentiator',
      },
      isSoftGate: true,
    },
    {
      id: 'D4-Q3',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 18,
      text: 'Is AI tool proficiency part of how you hire, onboard, or assess creative staff?',
      options: {
        A: 'No — AI skills are not part of our hiring or performance criteria',
        B: 'Mentioned occasionally in interviews; not a formal criterion',
        C: 'AI familiarity is valued and discussed in hiring; no formal benchmark',
        D: 'AI tool proficiency is in job descriptions, assessed in interviews, and included in onboarding',
      },
    },
    {
      id: 'D5-Q3',
      dimensionId: 'D5' as DimensionId,
      dimensionName: 'Process Maturity',
      order: 23,
      text: 'Do you have a defined process for briefing AI tools consistently — so outputs are predictable and brand-aligned?',
      options: {
        A: 'No — everyone prompts differently; outputs are inconsistent',
        B: 'Some people have developed their own prompting style; nothing shared',
        C: 'Shared prompting guidelines exist for specific use cases',
        D: 'Documented briefing framework for AI: brand tone, output format, quality criteria — trained across the team',
      },
    },
  ],
  technology_software: [
    {
      id: 'D1-Q1',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 1,
      text: 'Does your product or service roadmap include AI as a core capability — not a nice-to-have — in the next 12 months?',
      options: {
        A: 'No — AI is not on the product roadmap',
        B: 'Mentioned in planning but no committed features or timeline',
        C: 'At least one AI feature is defined and resourced in the current roadmap',
        D: 'AI is a central architectural component with dedicated engineering capacity and a multi-quarter roadmap',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D1-Q2', 'D1-Q3'],
      autoScoreOnSkip: 0.5,
      isHardGate: true,
    },
    {
      id: 'D1-Q3',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 3,
      text: 'Do you have proprietary or structured datasets that could be used to train, fine-tune, or ground AI models?',
      options: {
        A: 'No — we don\'t have structured proprietary data',
        B: 'Some structured data exists but it\'s not organised for ML use',
        C: 'Usable datasets exist; not yet prepared for training or fine-tuning',
        D: 'Clean, labelled proprietary datasets prepared and ready for model work',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D2-Q1',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 6,
      text: 'Do you have dedicated engineering budget or headcount allocated to AI development — not just AI tool subscriptions?',
      options: {
        A: 'No dedicated AI engineering resource or budget',
        B: 'Individuals experimenting on the side; no formal allocation',
        C: 'Part-time allocation exists; AI is one of several engineering priorities',
        D: 'Dedicated AI engineer(s) or ML resource with ring-fenced budget and quarterly OKRs',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D2-Q2'],
      autoScoreOnSkip: 0.5,
      isSoftGate: true,
    },
    {
      id: 'D3-Q3',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 13,
      text: 'Does your product have an AI safety or responsible AI framework — covering output reliability, bias, and user harm?',
      options: {
        A: 'No — we haven\'t built an AI safety framework into the product',
        B: 'Informally considered but not documented or tested',
        C: 'Basic safety considerations documented; some testing in place',
        D: 'Formal AI safety framework: bias testing, output monitoring, human override mechanisms, incident process',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'Are you integrating AI capabilities into your product via APIs (e.g. OpenAI, Anthropic, Google) or building proprietary models?',
      options: {
        A: 'Neither — AI is not integrated into the product',
        B: 'Exploring or prototyping; not in production',
        C: 'At least one AI integration in production for a defined feature',
        D: 'Multiple AI integrations in production with monitoring, fallback logic, and versioned model management',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q4',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 29,
      text: 'Do you monitor your AI model outputs in production — for accuracy, drift, latency, and unexpected behaviour?',
      options: {
        A: 'No monitoring in place for AI outputs',
        B: 'Basic uptime monitoring only; no output quality tracking',
        C: 'Some output sampling and periodic review; not systematic',
        D: 'Automated monitoring: accuracy metrics, drift detection, latency alerts, anomaly flagging — reviewed regularly',
      },
    },
    {
      id: 'D4-Q4',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 19,
      text: 'Do you have in-house ML, data science, or AI engineering capability — or a defined plan to build it?',
      options: {
        A: 'No in-house capability and no plan to build it',
        B: 'No dedicated resource; relying on AI tool APIs without engineering depth',
        C: 'At least one person with ML/data science skills, though AI is not their primary focus',
        D: 'Dedicated AI/ML engineering capability or a funded hiring plan to build it within 6 months',
      },
    },
  ],
  trade_field_services: [
    {
      id: 'D1-Q2',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 2,
      text: 'Do you collect data from jobs, sites, or equipment in a structured digital format — not just paper or memory?',
      options: {
        A: 'No — job data is on paper, in people\'s heads, or in photos',
        B: 'Some digital records exist but they\'re inconsistent and hard to access',
        C: 'Most job data goes into a digital system; some gaps remain',
        D: 'All job data captured digitally in a consistent format; accessible to the business',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D2-Q1',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 6,
      text: 'Has your leadership discussed how technology could reduce delays, errors, or cost overruns in the next 2 years?',
      options: {
        A: 'No — technology improvements haven\'t come up in a structured way',
        B: 'Mentioned in passing; no follow-through or named owner',
        C: 'At least one initiative discussed with a named next step',
        D: 'Active technology improvement programme with defined projects, owners, and timelines',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D2-Q2'],
      autoScoreOnSkip: 0.5,
      isSoftGate: true,
    },
    {
      id: 'D3-Q3',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 13,
      text: 'Are there health, safety, or regulatory rules that govern how decisions are made on your sites or with your equipment?',
      options: {
        A: 'Yes but AI is not considered in our H&S or compliance processes',
        B: 'Aware AI could intersect with H&S; haven\'t formally assessed it',
        C: 'H&S team has been briefed on AI; preliminary risk considerations in place',
        D: 'AI use on sites or equipment is formally assessed against H&S regulations; documented controls in place',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D4-Q3',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 18,
      text: 'How comfortable is your workforce — including site or field workers — with using smartphones or tablets for work tasks?',
      options: {
        A: 'Most field workers avoid digital tools; preference for paper or verbal',
        B: 'Mixed — office staff comfortable, field workers vary widely',
        C: 'Most workers use smartphones for basic tasks; some resistance to new apps',
        D: 'Workforce digitally literate at a practical level; new apps adopted with minimal friction',
      },
    },
    {
      id: 'D5-Q1',
      dimensionId: 'D5' as DimensionId,
      dimensionName: 'Process Maturity',
      order: 21,
      text: 'Are your core operational processes — job scheduling, quoting, site delivery, invoicing — documented and consistent across the team?',
      options: {
        A: 'Almost none — each job is handled however the person in charge decides',
        B: 'Some processes written down by individual managers; not standardised',
        C: 'Key processes documented for most roles; not always followed consistently',
        D: 'Standardised, documented processes for all core operations; reviewed regularly; accessible to the team',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D5-Q2'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'Do you currently use any digital tools for job scheduling, quoting, project tracking, or site management?',
      options: {
        A: 'No — everything is managed manually or by phone',
        B: 'Basic tools (spreadsheets, WhatsApp) but nothing purpose-built',
        C: 'At least one purpose-built operational tool (e.g. job management software) in active use',
        D: 'Integrated digital operations: job management, scheduling, and reporting in connected systems',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q4',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 29,
      text: 'Do you use any sensor, monitoring, or IoT technology on equipment, vehicles, or sites?',
      options: {
        A: 'No — no sensor or monitoring technology in use',
        B: 'Basic GPS tracking only; no data feeding into decision-making',
        C: 'Some monitoring in place (GPS, telematics); data reviewed occasionally',
        D: 'Active sensor or IoT infrastructure; data feeds into operational decisions in near-real time',
      },
    },
    {
      id: 'D5-Q5',
      dimensionId: 'D5' as DimensionId,
      dimensionName: 'Process Maturity',
      order: 25,
      text: 'Do you track which jobs, clients, or contract types are most and least profitable?',
      options: {
        A: 'No — we invoice and move on; profitability by job isn\'t tracked',
        B: 'Roughly — some sense of which jobs go well but not data-driven',
        C: 'We track it for major contracts; smaller jobs aren\'t analysed',
        D: 'Job profitability tracked consistently; reviewed regularly; informs quoting and business decisions',
      },
    },
  ],
  retail_hospitality: [
    {
      id: 'D1-Q2',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 2,
      text: 'Do you have a single view of customer purchase history and behaviour — accessible without manual work?',
      options: {
        A: 'No — customer data is fragmented across POS, email, and spreadsheets',
        B: 'Some data exists in a CRM or system but it\'s incomplete and not trusted',
        C: 'Customer data consolidated in one system; usable but not fully clean',
        D: 'Single customer view with purchase history, preferences, and engagement data — accessible and reliable',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D2-Q5',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 10,
      text: 'Has your leadership explored how AI could reduce customer acquisition costs or increase repeat purchase rates?',
      options: {
        A: 'No — AI hasn\'t been considered in the context of customer economics',
        B: 'Vague awareness that AI could help; no specific exploration',
        C: '1–2 use cases identified (e.g. personalisation, churn prediction); not yet planned',
        D: 'Defined AI strategy targeting specific customer metrics: acquisition cost, LTV, repeat rate — with owner and timeline',
      },
      isSoftGate: true,
    },
    {
      id: 'D5-Q3',
      dimensionId: 'D5' as DimensionId,
      dimensionName: 'Process Maturity',
      order: 23,
      text: 'How do you currently forecast demand and manage stock levels?',
      options: {
        A: 'Gut feel and experience — no data-driven approach',
        B: 'Basic spreadsheet or manual order tracking; reactive rather than predictive',
        C: 'Reviewing sales data periodically to inform orders; some forward planning',
        D: 'Data-driven demand forecasting with defined reorder points, seasonal planning, and waste tracking',
      },
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'Do you currently personalise offers, recommendations, or communications to individual customers?',
      options: {
        A: 'No — all customers receive the same communications and offers',
        B: 'Basic segmentation (e.g. loyalty tiers) but not individual personalisation',
        C: 'Some personalisation in email or offers based on purchase history',
        D: 'Dynamic personalisation across channels: email, on-site, in-app — driven by real-time behavioural data',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D6-Q4',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 29,
      text: 'Do you collect customer feedback digitally and analyse it systematically?',
      options: {
        A: 'No — feedback comes in ad hoc and isn\'t captured or reviewed',
        B: 'Collected occasionally (surveys, reviews) but not systematically analysed',
        C: 'Regular feedback collection with periodic review by a named person',
        D: 'Systematic feedback loop: collected across touchpoints, analysed for themes, feeding into operations and product decisions',
      },
    },
    {
      id: 'D4-Q3',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 18,
      text: 'Does your team have experience using ecommerce platforms, POS analytics, or CRM dashboards?',
      options: {
        A: 'No digital tool experience; team works manually',
        B: 'Some individuals comfortable with one platform; team-wide variance is high',
        C: 'Most team members can use the main operational platforms with guidance',
        D: 'Team digitally proficient across relevant platforms; can extract and act on data independently',
      },
    },
    {
      id: 'D1-Q4',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 4,
      text: 'Do you track inventory levels digitally and in real time — or close to it?',
      options: {
        A: 'No — inventory is counted manually on a periodic basis',
        B: 'Tracked in a spreadsheet or basic system; not real time',
        C: 'Inventory system in place; updated regularly but with some lag',
        D: 'Real-time or near-real-time digital inventory tracking integrated with sales data',
      },
      isHardGate: true,
    },
    {
      id: 'D5-Q4',
      dimensionId: 'D5' as DimensionId,
      dimensionName: 'Process Maturity',
      order: 24,
      text: 'Do you use any automated tools for email marketing, social media scheduling, or customer communications?',
      options: {
        A: 'No automation — all communications are manual',
        B: 'One or two personal automations; not team-wide or strategic',
        C: 'At least one automated communication workflow in use (e.g. welcome email, abandoned cart)',
        D: 'Multi-channel automated communications with segmentation, triggers, and performance tracking',
      },
    },
  ],
  health_wellbeing: [
    {
      id: 'D1-Q2',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 2,
      text: 'Is patient or client data stored in a system that is compliant with ICO registration and UK GDPR requirements?',
      options: {
        A: 'Not sure — we haven\'t formally assessed our data storage against ICO requirements',
        B: 'We use standard software but haven\'t verified specific compliance',
        C: 'ICO registered; data storage reviewed for compliance; some gaps identified',
        D: 'Fully compliant: ICO registered, data storage verified, retention and deletion policies active',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D2-Q5',
      dimensionId: 'D2' as DimensionId,
      dimensionName: 'Leadership & Strategy',
      order: 10,
      text: 'Does your leadership understand the difference between administrative AI use and AI used in or near clinical decisions?',
      options: {
        A: 'No distinction has been considered',
        B: 'Vaguely understood but not articulated or documented',
        C: 'Discussed and informally agreed; not formalised as a governance boundary',
        D: 'Documented policy defining administrative AI vs. clinical AI with different governance requirements for each',
      },
      isSoftGate: true,
    },
    {
      id: 'D3-Q1',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 11,
      text: 'Are you registered with the ICO and do you have a named Data Protection Officer or privacy lead?',
      options: {
        A: 'Not registered with ICO and no named privacy lead',
        B: 'ICO registered but no named DPO or privacy lead',
        C: 'ICO registered with an informal privacy lead who handles queries',
        D: 'ICO registered, named DPO or privacy lead with documented responsibilities and regular review',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D3-Q2', 'D3-Q3'],
      autoScoreOnSkip: 0.5,
      isHardGate: true,
    },
    {
      id: 'D3-Q3',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 13,
      text: 'Do you have a policy on using AI tools that may process patient or client health data — separate from your general data policy?',
      options: {
        A: 'No — AI tools are not addressed in any data policy',
        B: 'General data policy exists; AI is not specifically addressed',
        C: 'AI mentioned in data policy; health data handling in AI tools not specifically governed',
        D: 'Dedicated AI and health data policy: approved tools, consent requirements, data minimisation, audit trail',
      },
      isBranchChild: true,
      isHardGate: true,
    },
    {
      id: 'D3-Q4',
      dimensionId: 'D3' as DimensionId,
      dimensionName: 'Governance & Risk',
      order: 14,
      text: 'Have you assessed whether any AI tools you use are classified as medical devices under MHRA guidance?',
      options: {
        A: 'No — this hasn\'t been considered',
        B: 'Aware the question exists but haven\'t investigated specific tools',
        C: 'Checked key tools; some ambiguity remains on one or two',
        D: 'All AI tools assessed against MHRA criteria; medical device tools identified and managed under appropriate regulatory pathway',
      },
      isHardGate: true,
    },
    {
      id: 'D6-Q1',
      dimensionId: 'D6' as DimensionId,
      dimensionName: 'AI Usage & Adoption',
      order: 26,
      text: 'Are you currently using any AI-assisted tools for administrative tasks — scheduling, triage, notes, billing?',
      options: {
        A: 'No AI tools in use for any administrative tasks',
        B: 'One individual uses AI for personal admin (e.g. drafting); not a practice decision',
        C: 'At least one AI tool in use for administrative tasks with basic oversight',
        D: 'Defined AI tools for admin with documented use, staff training, and periodic review of appropriateness',
      },
      isBranchParent: true,
      branchTrigger: 'A',
      childQuestions: ['D6-Q2', 'D6-Q3'],
      autoScoreOnSkip: 0.5,
    },
    {
      id: 'D1-Q4',
      dimensionId: 'D1' as DimensionId,
      dimensionName: 'Data & Knowledge Foundations',
      order: 4,
      text: 'Do you collect patient or client outcome data in a structured format that could be used for service improvement?',
      options: {
        A: 'No — outcome data is not systematically collected',
        B: 'Some outcome notes exist in records but not structured or analysed',
        C: 'Outcome data collected for some patients; not consistent across all care types',
        D: 'Structured outcome data collected consistently; reviewed periodically; used in service decisions',
      },
      isHardGate: true,
    },
    {
      id: 'D4-Q3',
      dimensionId: 'D4' as DimensionId,
      dimensionName: 'People & Change Readiness',
      order: 18,
      text: 'Have any staff received training on data protection obligations specifically as they relate to digital health tools?',
      options: {
        A: 'No data protection training specific to digital tools has taken place',
        B: 'General GDPR training only; no digital health tool-specific content',
        C: 'At least one team training session on data protection in digital health tools',
        D: 'Regular role-specific data protection training including AI and digital tool obligations; completion tracked',
      },
    },
  ],
};


// ─── BUILD QUESTION SET ───
// Merges universal questions with sector-specific overrides.
// Start with universal array, then for each override, find matching Q-ID and replace.
export function buildQuestionSet(sector: Sector): Question[] {
  const overrideList = sectorOverrides[sector] || [];
  const overrideMap = new Map(overrideList.map(q => [q.id, q]));
  
  return universalQuestions.map(q => {
    const override = overrideMap.get(q.id);
    if (override) {
      // Replace text and options, keep all metadata from override (which inherits from universal)
      return override;
    }
    return q;
  });
}
